// IATA air waybill numbering.
//
// An AWB number is 11 digits: a 3-digit airline prefix, a 7-digit running
// serial, and a final check digit.
//
// The check digit is the serial modulo 7. That is why it only ever runs 0-6
// and never reaches 7, 8 or 9 - and why, for consecutive serials, it simply
// steps up by one and wraps back to 0:
//
//   125 1000000 1   (1000000 % 7 = 1)
//   125 1000001 2
//   ...
//   125 1000005 6
//   125 1000006 0   <- wraps here, the serial keeps counting normally
//   125 1000007 1
//
// So a series is generated by incrementing the SERIAL and recomputing the
// check digit each time - never by counting the last digit upwards.

const PREFIX_LENGTH = 3;
const SERIAL_LENGTH = 7;
const MAX_SERIAL = 9999999;

const isDigits = (value, length) =>
  typeof value === 'string' && new RegExp(`^\\d{${length}}$`).test(value);

const checkDigitFor = (serial) => String(Number(serial) % 7);

const padSerial = (serial) => String(serial).padStart(SERIAL_LENGTH, '0');

// Full 11-digit number for a given prefix + numeric serial.
const buildNumber = (prefix, serial) =>
  `${prefix}${padSerial(serial)}${checkDigitFor(serial)}`;

// Human-readable form used in the UI and on the job: 125-10000001.
const formatNumber = (awbNumber) =>
  `${awbNumber.slice(0, PREFIX_LENGTH)}-${awbNumber.slice(PREFIX_LENGTH)}`;

/**
 * Validates the 3-digit airline prefix and the 8 digits the user typed
 * (7-digit serial followed by its check digit).
 *
 * The typed check digit is verified rather than ignored: it is the one part
 * of the number that can be derived, so a mismatch is a typo, and letting it
 * through would put a number in stock that no airline will accept.
 *
 * @returns {{ok: true, prefix, serial}} or {{ok: false, error}}
 */
const parseEntry = (prefix, code) => {
  const cleanPrefix = String(prefix ?? '').trim();
  const cleanCode = String(code ?? '').trim().replace(/[\s-]/g, '');

  if (!isDigits(cleanPrefix, PREFIX_LENGTH)) {
    return { ok: false, error: 'Airline prefix must be exactly 3 digits.' };
  }
  if (!isDigits(cleanCode, SERIAL_LENGTH + 1)) {
    return { ok: false, error: 'AWB number must be exactly 8 digits (7-digit serial plus check digit).' };
  }

  const serialPart = cleanCode.slice(0, SERIAL_LENGTH);
  const typedCheck = cleanCode.slice(SERIAL_LENGTH);
  const expectedCheck = checkDigitFor(serialPart);

  if (typedCheck !== expectedCheck) {
    // Worded for the person who has to fix it. The obvious misreading is that
    // any digit 0-6 is acceptable; in fact exactly one is, because the digit is
    // calculated from the serial rather than chosen. Spelling out the division
    // and showing the corrected number heads that question off.
    return {
      ok: false,
      error:
        `The last digit should be ${expectedCheck}, not ${typedCheck}. It is calculated, not free choice: ` +
        `${serialPart} divided by 7 leaves ${expectedCheck}, so the only valid number for this serial is ` +
        `${cleanPrefix}-${serialPart}${expectedCheck}. Check the AWB document - either a digit in the ` +
        `serial is wrong, or the last digit is.`,
    };
  }

  return { ok: true, prefix: cleanPrefix, serial: Number(serialPart) };
};

/**
 * Builds `count` consecutive numbers starting at `startSerial`.
 * Stops early rather than rolling past the 7-digit ceiling.
 */
const generateSeries = (prefix, startSerial, count) => {
  const total = Math.max(1, Math.floor(Number(count) || 1));
  const rows = [];

  for (let i = 0; i < total; i++) {
    const serial = startSerial + i;
    if (serial > MAX_SERIAL) break;
    rows.push({
      prefix,
      serial: padSerial(serial),
      checkDigit: checkDigitFor(serial),
      awbNumber: buildNumber(prefix, serial),
    });
  }

  return rows;
};

module.exports = {
  PREFIX_LENGTH,
  SERIAL_LENGTH,
  MAX_SERIAL,
  checkDigitFor,
  padSerial,
  buildNumber,
  formatNumber,
  parseEntry,
  generateSeries,
};
